/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.163
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FeeWise.Client.OpenAPIDateConverter;

namespace FeeWise.Model
{
    /// <summary>
    /// ChargePaymentDetails
    /// </summary>
    [DataContract(Name = "ChargePaymentDetails")]
    public partial class ChargePaymentDetails : IEquatable<ChargePaymentDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChargePaymentDetails" /> class.
        /// </summary>
        /// <param name="charge">charge.</param>
        /// <param name="paymentDetails">paymentDetails.</param>
        public ChargePaymentDetails(Charge charge = default(Charge), PaymentDetails paymentDetails = default(PaymentDetails))
        {
            this.Charge = charge;
            this.PaymentDetails = paymentDetails;
        }

        /// <summary>
        /// Gets or Sets Charge
        /// </summary>
        [DataMember(Name = "charge", EmitDefaultValue = false)]
        public Charge Charge { get; set; }

        /// <summary>
        /// Gets or Sets PaymentDetails
        /// </summary>
        [DataMember(Name = "payment_details", EmitDefaultValue = false)]
        public PaymentDetails PaymentDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChargePaymentDetails {\n");
            sb.Append("  Charge: ").Append(Charge).Append("\n");
            sb.Append("  PaymentDetails: ").Append(PaymentDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChargePaymentDetails);
        }

        /// <summary>
        /// Returns true if ChargePaymentDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of ChargePaymentDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChargePaymentDetails input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Charge == input.Charge ||
                    (this.Charge != null &&
                    this.Charge.Equals(input.Charge))
                ) && 
                (
                    this.PaymentDetails == input.PaymentDetails ||
                    (this.PaymentDetails != null &&
                    this.PaymentDetails.Equals(input.PaymentDetails))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Charge != null)
                {
                    hashCode = (hashCode * 59) + this.Charge.GetHashCode();
                }
                if (this.PaymentDetails != null)
                {
                    hashCode = (hashCode * 59) + this.PaymentDetails.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
