/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.164
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FeeWise.Client.OpenAPIDateConverter;

namespace FeeWise.Model
{
    /// <summary>
    /// A webhook event that&#39;s emitted whenever a firm&#39;s pricing settings are changed.
    /// </summary>
    [DataContract(Name = "FirmPricingUpdatedEvent")]
    public partial class FirmPricingUpdatedEvent : IEquatable<FirmPricingUpdatedEvent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FirmPricingUpdatedEvent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FirmPricingUpdatedEvent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FirmPricingUpdatedEvent" /> class.
        /// </summary>
        /// <param name="firmId">firmId (required).</param>
        /// <param name="metadata">Set of key value pairs attached to the object when it was created..</param>
        /// <param name="products">products (required).</param>
        public FirmPricingUpdatedEvent(Guid firmId = default(Guid), Dictionary<string, string> metadata = default(Dictionary<string, string>), List<Product> products = default(List<Product>))
        {
            this.FirmId = firmId;
            // to ensure "products" is required (not null)
            if (products == null)
            {
                throw new ArgumentNullException("products is a required property for FirmPricingUpdatedEvent and cannot be null");
            }
            this.Products = products;
            this.Metadata = metadata;
        }

        /// <summary>
        /// Gets or Sets FirmId
        /// </summary>
        [DataMember(Name = "firm_id", IsRequired = true, EmitDefaultValue = true)]
        public Guid FirmId { get; set; }

        /// <summary>
        /// Set of key value pairs attached to the object when it was created.
        /// </summary>
        /// <value>Set of key value pairs attached to the object when it was created.</value>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// Gets or Sets Products
        /// </summary>
        [DataMember(Name = "products", IsRequired = true, EmitDefaultValue = true)]
        public List<Product> Products { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FirmPricingUpdatedEvent {\n");
            sb.Append("  FirmId: ").Append(FirmId).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Products: ").Append(Products).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FirmPricingUpdatedEvent);
        }

        /// <summary>
        /// Returns true if FirmPricingUpdatedEvent instances are equal
        /// </summary>
        /// <param name="input">Instance of FirmPricingUpdatedEvent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FirmPricingUpdatedEvent input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.FirmId == input.FirmId ||
                    (this.FirmId != null &&
                    this.FirmId.Equals(input.FirmId))
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    this.Metadata != null &&
                    input.Metadata != null &&
                    this.Metadata.SequenceEqual(input.Metadata)
                ) && 
                (
                    this.Products == input.Products ||
                    this.Products != null &&
                    input.Products != null &&
                    this.Products.SequenceEqual(input.Products)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FirmId != null)
                {
                    hashCode = (hashCode * 59) + this.FirmId.GetHashCode();
                }
                if (this.Metadata != null)
                {
                    hashCode = (hashCode * 59) + this.Metadata.GetHashCode();
                }
                if (this.Products != null)
                {
                    hashCode = (hashCode * 59) + this.Products.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
