/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.163
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FeeWise.Client.OpenAPIDateConverter;

namespace FeeWise.Model
{
    /// <summary>
    /// Branding for a party (firm or channel partner)
    /// </summary>
    [DataContract(Name = "PartyBranding")]
    public partial class PartyBranding : IEquatable<PartyBranding>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartyBranding" /> class.
        /// </summary>
        /// <param name="logo">logo.</param>
        /// <param name="icon">icon.</param>
        /// <param name="colour">colour.</param>
        /// <param name="brandPrimaryColour">brandPrimaryColour.</param>
        /// <param name="mainTextColour">mainTextColour.</param>
        /// <param name="tableHeaderBackgroundColour">tableHeaderBackgroundColour.</param>
        /// <param name="tableHeaderTextColour">tableHeaderTextColour.</param>
        public PartyBranding(string logo = default(string), string icon = default(string), string colour = default(string), string brandPrimaryColour = default(string), string mainTextColour = default(string), string tableHeaderBackgroundColour = default(string), string tableHeaderTextColour = default(string))
        {
            this.Logo = logo;
            this.Icon = icon;
            this.Colour = colour;
            this.BrandPrimaryColour = brandPrimaryColour;
            this.MainTextColour = mainTextColour;
            this.TableHeaderBackgroundColour = tableHeaderBackgroundColour;
            this.TableHeaderTextColour = tableHeaderTextColour;
        }

        /// <summary>
        /// Gets or Sets Logo
        /// </summary>
        [DataMember(Name = "logo", EmitDefaultValue = false)]
        public string Logo { get; set; }

        /// <summary>
        /// Gets or Sets Icon
        /// </summary>
        [DataMember(Name = "icon", EmitDefaultValue = false)]
        public string Icon { get; set; }

        /// <summary>
        /// Gets or Sets Colour
        /// </summary>
        [DataMember(Name = "colour", EmitDefaultValue = false)]
        public string Colour { get; set; }

        /// <summary>
        /// Gets or Sets BrandPrimaryColour
        /// </summary>
        [DataMember(Name = "brand_primary_colour", EmitDefaultValue = false)]
        public string BrandPrimaryColour { get; set; }

        /// <summary>
        /// Gets or Sets MainTextColour
        /// </summary>
        [DataMember(Name = "main_text_colour", EmitDefaultValue = false)]
        public string MainTextColour { get; set; }

        /// <summary>
        /// Gets or Sets TableHeaderBackgroundColour
        /// </summary>
        [DataMember(Name = "table_header_background_colour", EmitDefaultValue = false)]
        public string TableHeaderBackgroundColour { get; set; }

        /// <summary>
        /// Gets or Sets TableHeaderTextColour
        /// </summary>
        [DataMember(Name = "table_header_text_colour", EmitDefaultValue = false)]
        public string TableHeaderTextColour { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartyBranding {\n");
            sb.Append("  Logo: ").Append(Logo).Append("\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  Colour: ").Append(Colour).Append("\n");
            sb.Append("  BrandPrimaryColour: ").Append(BrandPrimaryColour).Append("\n");
            sb.Append("  MainTextColour: ").Append(MainTextColour).Append("\n");
            sb.Append("  TableHeaderBackgroundColour: ").Append(TableHeaderBackgroundColour).Append("\n");
            sb.Append("  TableHeaderTextColour: ").Append(TableHeaderTextColour).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PartyBranding);
        }

        /// <summary>
        /// Returns true if PartyBranding instances are equal
        /// </summary>
        /// <param name="input">Instance of PartyBranding to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PartyBranding input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Logo == input.Logo ||
                    (this.Logo != null &&
                    this.Logo.Equals(input.Logo))
                ) && 
                (
                    this.Icon == input.Icon ||
                    (this.Icon != null &&
                    this.Icon.Equals(input.Icon))
                ) && 
                (
                    this.Colour == input.Colour ||
                    (this.Colour != null &&
                    this.Colour.Equals(input.Colour))
                ) && 
                (
                    this.BrandPrimaryColour == input.BrandPrimaryColour ||
                    (this.BrandPrimaryColour != null &&
                    this.BrandPrimaryColour.Equals(input.BrandPrimaryColour))
                ) && 
                (
                    this.MainTextColour == input.MainTextColour ||
                    (this.MainTextColour != null &&
                    this.MainTextColour.Equals(input.MainTextColour))
                ) && 
                (
                    this.TableHeaderBackgroundColour == input.TableHeaderBackgroundColour ||
                    (this.TableHeaderBackgroundColour != null &&
                    this.TableHeaderBackgroundColour.Equals(input.TableHeaderBackgroundColour))
                ) && 
                (
                    this.TableHeaderTextColour == input.TableHeaderTextColour ||
                    (this.TableHeaderTextColour != null &&
                    this.TableHeaderTextColour.Equals(input.TableHeaderTextColour))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Logo != null)
                {
                    hashCode = (hashCode * 59) + this.Logo.GetHashCode();
                }
                if (this.Icon != null)
                {
                    hashCode = (hashCode * 59) + this.Icon.GetHashCode();
                }
                if (this.Colour != null)
                {
                    hashCode = (hashCode * 59) + this.Colour.GetHashCode();
                }
                if (this.BrandPrimaryColour != null)
                {
                    hashCode = (hashCode * 59) + this.BrandPrimaryColour.GetHashCode();
                }
                if (this.MainTextColour != null)
                {
                    hashCode = (hashCode * 59) + this.MainTextColour.GetHashCode();
                }
                if (this.TableHeaderBackgroundColour != null)
                {
                    hashCode = (hashCode * 59) + this.TableHeaderBackgroundColour.GetHashCode();
                }
                if (this.TableHeaderTextColour != null)
                {
                    hashCode = (hashCode * 59) + this.TableHeaderTextColour.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
