/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.197
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FeeWise.Client.OpenAPIDateConverter;

namespace FeeWise.Model
{
    /// <summary>
    /// Defines PaymentDetailType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PaymentDetailType
    {
        /// <summary>
        /// Enum Invoice for value: invoice
        /// </summary>
        [EnumMember(Value = "invoice")]
        Invoice = 1,

        /// <summary>
        /// Enum TrustDeposit for value: trust_deposit
        /// </summary>
        [EnumMember(Value = "trust_deposit")]
        TrustDeposit = 2,

        /// <summary>
        /// Enum Matter for value: matter
        /// </summary>
        [EnumMember(Value = "matter")]
        Matter = 3,

        /// <summary>
        /// Enum Debtor for value: debtor
        /// </summary>
        [EnumMember(Value = "debtor")]
        Debtor = 4

    }

}
