/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.164
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = FeeWise.Client.OpenAPIDateConverter;

namespace FeeWise.Model
{
    /// <summary>
    /// Defines RefundStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum RefundStatus
    {
        /// <summary>
        /// Enum Requested for value: Requested
        /// </summary>
        [EnumMember(Value = "Requested")]
        Requested = 1,

        /// <summary>
        /// Enum Processing for value: Processing
        /// </summary>
        [EnumMember(Value = "Processing")]
        Processing = 2,

        /// <summary>
        /// Enum Clearing for value: Clearing
        /// </summary>
        [EnumMember(Value = "Clearing")]
        Clearing = 3,

        /// <summary>
        /// Enum Complete for value: Complete
        /// </summary>
        [EnumMember(Value = "Complete")]
        Complete = 4,

        /// <summary>
        /// Enum Failed for value: Failed
        /// </summary>
        [EnumMember(Value = "Failed")]
        Failed = 5,

        /// <summary>
        /// Enum CancelledInternal for value: CancelledInternal
        /// </summary>
        [EnumMember(Value = "CancelledInternal")]
        CancelledInternal = 6,

        /// <summary>
        /// Enum CancelledFirm for value: CancelledFirm
        /// </summary>
        [EnumMember(Value = "CancelledFirm")]
        CancelledFirm = 7

    }

}
