/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.115
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing ApiKeyRotation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiKeyRotationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiKeyRotation
        //private ApiKeyRotation instance;

        public ApiKeyRotationTests()
        {
            // TODO uncomment below to create an instance of ApiKeyRotation
            //instance = new ApiKeyRotation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiKeyRotation
        /// </summary>
        [Fact]
        public void ApiKeyRotationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiKeyRotation
            //Assert.IsType<ApiKeyRotation>(instance);
        }


        /// <summary>
        /// Test the property 'PreviousKeyExpiresHours'
        /// </summary>
        [Fact]
        public void PreviousKeyExpiresHoursTest()
        {
            // TODO unit test for the property 'PreviousKeyExpiresHours'
        }

    }

}
