/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.65
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing ArtifactReceipt
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArtifactReceiptTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArtifactReceipt
        //private ArtifactReceipt instance;

        public ArtifactReceiptTests()
        {
            // TODO uncomment below to create an instance of ArtifactReceipt
            //instance = new ArtifactReceipt();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArtifactReceipt
        /// </summary>
        [Fact]
        public void ArtifactReceiptInstanceTest()
        {
            // TODO uncomment below to test "IsType" ArtifactReceipt
            //Assert.IsType<ArtifactReceipt>(instance);
        }


        /// <summary>
        /// Test the property 'ReceiptId'
        /// </summary>
        [Fact]
        public void ReceiptIdTest()
        {
            // TODO unit test for the property 'ReceiptId'
        }
        /// <summary>
        /// Test the property 'ArtifactId'
        /// </summary>
        [Fact]
        public void ArtifactIdTest()
        {
            // TODO unit test for the property 'ArtifactId'
        }
        /// <summary>
        /// Test the property 'ArtifactType'
        /// </summary>
        [Fact]
        public void ArtifactTypeTest()
        {
            // TODO unit test for the property 'ArtifactType'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'AmountPaid'
        /// </summary>
        [Fact]
        public void AmountPaidTest()
        {
            // TODO unit test for the property 'AmountPaid'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }

    }

}
