/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.67
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing CreateFirm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateFirmTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateFirm
        //private CreateFirm instance;

        public CreateFirmTests()
        {
            // TODO uncomment below to create an instance of CreateFirm
            //instance = new CreateFirm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateFirm
        /// </summary>
        [Fact]
        public void CreateFirmInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateFirm
            //Assert.IsType<CreateFirm>(instance);
        }


        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'OfficeAccount'
        /// </summary>
        [Fact]
        public void OfficeAccountTest()
        {
            // TODO unit test for the property 'OfficeAccount'
        }
        /// <summary>
        /// Test the property 'TrustAccount'
        /// </summary>
        [Fact]
        public void TrustAccountTest()
        {
            // TODO unit test for the property 'TrustAccount'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
