/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.64
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing CreateFirmResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateFirmResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateFirmResponse
        //private CreateFirmResponse instance;

        public CreateFirmResponseTests()
        {
            // TODO uncomment below to create an instance of CreateFirmResponse
            //instance = new CreateFirmResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateFirmResponse
        /// </summary>
        [Fact]
        public void CreateFirmResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateFirmResponse
            //Assert.IsType<CreateFirmResponse>(instance);
        }


        /// <summary>
        /// Test the property 'FirmDetails'
        /// </summary>
        [Fact]
        public void FirmDetailsTest()
        {
            // TODO unit test for the property 'FirmDetails'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Accounts'
        /// </summary>
        [Fact]
        public void AccountsTest()
        {
            // TODO unit test for the property 'Accounts'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

    }

}
