/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.120
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerPaymentMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerPaymentMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerPaymentMethod
        //private CustomerPaymentMethod instance;

        public CustomerPaymentMethodTests()
        {
            // TODO uncomment below to create an instance of CustomerPaymentMethod
            //instance = new CustomerPaymentMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerPaymentMethod
        /// </summary>
        [Fact]
        public void CustomerPaymentMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerPaymentMethod
            //Assert.IsType<CustomerPaymentMethod>(instance);
        }


        /// <summary>
        /// Test the property 'PaymentToken'
        /// </summary>
        [Fact]
        public void PaymentTokenTest()
        {
            // TODO unit test for the property 'PaymentToken'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'Card'
        /// </summary>
        [Fact]
        public void CardTest()
        {
            // TODO unit test for the property 'Card'
        }
        /// <summary>
        /// Test the property 'Debit'
        /// </summary>
        [Fact]
        public void DebitTest()
        {
            // TODO unit test for the property 'Debit'
        }

    }

}
