/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.108
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorResponseErrorContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorResponseErrorContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorResponseErrorContext
        //private ErrorResponseErrorContext instance;

        public ErrorResponseErrorContextTests()
        {
            // TODO uncomment below to create an instance of ErrorResponseErrorContext
            //instance = new ErrorResponseErrorContext();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorResponseErrorContext
        /// </summary>
        [Fact]
        public void ErrorResponseErrorContextInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorResponseErrorContext
            //Assert.IsType<ErrorResponseErrorContext>(instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'DeclineCode'
        /// </summary>
        [Fact]
        public void DeclineCodeTest()
        {
            // TODO unit test for the property 'DeclineCode'
        }

    }

}
