/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.197
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing FirmArtifactSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FirmArtifactSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FirmArtifactSummary
        //private FirmArtifactSummary instance;

        public FirmArtifactSummaryTests()
        {
            // TODO uncomment below to create an instance of FirmArtifactSummary
            //instance = new FirmArtifactSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FirmArtifactSummary
        /// </summary>
        [Fact]
        public void FirmArtifactSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" FirmArtifactSummary
            //Assert.IsType<FirmArtifactSummary>(instance);
        }


        /// <summary>
        /// Test the property 'ArtifactType'
        /// </summary>
        [Fact]
        public void ArtifactTypeTest()
        {
            // TODO unit test for the property 'ArtifactType'
        }
        /// <summary>
        /// Test the property 'ArtifactId'
        /// </summary>
        [Fact]
        public void ArtifactIdTest()
        {
            // TODO unit test for the property 'ArtifactId'
        }
        /// <summary>
        /// Test the property 'ExternalArtifactId'
        /// </summary>
        [Fact]
        public void ExternalArtifactIdTest()
        {
            // TODO unit test for the property 'ExternalArtifactId'
        }
        /// <summary>
        /// Test the property 'ArtifactNumber'
        /// </summary>
        [Fact]
        public void ArtifactNumberTest()
        {
            // TODO unit test for the property 'ArtifactNumber'
        }
        /// <summary>
        /// Test the property 'MatterId'
        /// </summary>
        [Fact]
        public void MatterIdTest()
        {
            // TODO unit test for the property 'MatterId'
        }
        /// <summary>
        /// Test the property 'ExternalMatterId'
        /// </summary>
        [Fact]
        public void ExternalMatterIdTest()
        {
            // TODO unit test for the property 'ExternalMatterId'
        }
        /// <summary>
        /// Test the property 'MatterNumber'
        /// </summary>
        [Fact]
        public void MatterNumberTest()
        {
            // TODO unit test for the property 'MatterNumber'
        }
        /// <summary>
        /// Test the property 'MatterType'
        /// </summary>
        [Fact]
        public void MatterTypeTest()
        {
            // TODO unit test for the property 'MatterType'
        }
        /// <summary>
        /// Test the property 'AmountDue'
        /// </summary>
        [Fact]
        public void AmountDueTest()
        {
            // TODO unit test for the property 'AmountDue'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'DebtorId'
        /// </summary>
        [Fact]
        public void DebtorIdTest()
        {
            // TODO unit test for the property 'DebtorId'
        }
        /// <summary>
        /// Test the property 'DebtorExternalId'
        /// </summary>
        [Fact]
        public void DebtorExternalIdTest()
        {
            // TODO unit test for the property 'DebtorExternalId'
        }
        /// <summary>
        /// Test the property 'DebtorName'
        /// </summary>
        [Fact]
        public void DebtorNameTest()
        {
            // TODO unit test for the property 'DebtorName'
        }
        /// <summary>
        /// Test the property 'DebtorEmail'
        /// </summary>
        [Fact]
        public void DebtorEmailTest()
        {
            // TODO unit test for the property 'DebtorEmail'
        }
        /// <summary>
        /// Test the property 'DebtorPhoneNumber'
        /// </summary>
        [Fact]
        public void DebtorPhoneNumberTest()
        {
            // TODO unit test for the property 'DebtorPhoneNumber'
        }
        /// <summary>
        /// Test the property 'LastUpdatedAt'
        /// </summary>
        [Fact]
        public void LastUpdatedAtTest()
        {
            // TODO unit test for the property 'LastUpdatedAt'
        }
        /// <summary>
        /// Test the property 'FeewisePaymentReferenceNumber'
        /// </summary>
        [Fact]
        public void FeewisePaymentReferenceNumberTest()
        {
            // TODO unit test for the property 'FeewisePaymentReferenceNumber'
        }
        /// <summary>
        /// Test the property 'PaymentUrl'
        /// </summary>
        [Fact]
        public void PaymentUrlTest()
        {
            // TODO unit test for the property 'PaymentUrl'
        }

    }

}
