/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.64
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing GetMagicLink200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetMagicLink200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetMagicLink200Response
        //private GetMagicLink200Response instance;

        public GetMagicLink200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetMagicLink200Response
            //instance = new GetMagicLink200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetMagicLink200Response
        /// </summary>
        [Fact]
        public void GetMagicLink200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetMagicLink200Response
            //Assert.IsType<GetMagicLink200Response>(instance);
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Expires'
        /// </summary>
        [Fact]
        public void ExpiresTest()
        {
            // TODO unit test for the property 'Expires'
        }

    }

}
