/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.81
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing GetPartnerBranding200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPartnerBranding200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPartnerBranding200Response
        //private GetPartnerBranding200Response instance;

        public GetPartnerBranding200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetPartnerBranding200Response
            //instance = new GetPartnerBranding200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPartnerBranding200Response
        /// </summary>
        [Fact]
        public void GetPartnerBranding200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPartnerBranding200Response
            //Assert.IsType<GetPartnerBranding200Response>(instance);
        }


        /// <summary>
        /// Test the property 'Branding'
        /// </summary>
        [Fact]
        public void BrandingTest()
        {
            // TODO unit test for the property 'Branding'
        }

    }

}
