/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.48
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing MatterRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatterRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MatterRequest
        //private MatterRequest instance;

        public MatterRequestTests()
        {
            // TODO uncomment below to create an instance of MatterRequest
            //instance = new MatterRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MatterRequest
        /// </summary>
        [Fact]
        public void MatterRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MatterRequest
            //Assert.IsType<MatterRequest>(instance);
        }


        /// <summary>
        /// Test the property 'FirmId'
        /// </summary>
        [Fact]
        public void FirmIdTest()
        {
            // TODO unit test for the property 'FirmId'
        }
        /// <summary>
        /// Test the property 'Matter'
        /// </summary>
        [Fact]
        public void MatterTest()
        {
            // TODO unit test for the property 'Matter'
        }
        /// <summary>
        /// Test the property 'Debtor'
        /// </summary>
        [Fact]
        public void DebtorTest()
        {
            // TODO unit test for the property 'Debtor'
        }
        /// <summary>
        /// Test the property 'Artifacts'
        /// </summary>
        [Fact]
        public void ArtifactsTest()
        {
            // TODO unit test for the property 'Artifacts'
        }

    }

}
