/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.91
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentTokenResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentTokenResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentTokenResponse
        //private PaymentTokenResponse instance;

        public PaymentTokenResponseTests()
        {
            // TODO uncomment below to create an instance of PaymentTokenResponse
            //instance = new PaymentTokenResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentTokenResponse
        /// </summary>
        [Fact]
        public void PaymentTokenResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentTokenResponse
            //Assert.IsType<PaymentTokenResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Debtor'
        /// </summary>
        [Fact]
        public void DebtorTest()
        {
            // TODO unit test for the property 'Debtor'
        }
        /// <summary>
        /// Test the property 'PaymentToken'
        /// </summary>
        [Fact]
        public void PaymentTokenTest()
        {
            // TODO unit test for the property 'PaymentToken'
        }
        /// <summary>
        /// Test the property 'CaptureUri'
        /// </summary>
        [Fact]
        public void CaptureUriTest()
        {
            // TODO unit test for the property 'CaptureUri'
        }
        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }

    }

}
