/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.103
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing Payouts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayoutsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Payouts
        //private Payouts instance;

        public PayoutsTests()
        {
            // TODO uncomment below to create an instance of Payouts
            //instance = new Payouts();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Payouts
        /// </summary>
        [Fact]
        public void PayoutsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Payouts
            //Assert.IsType<Payouts>(instance);
        }


        /// <summary>
        /// Test the property '_Payouts'
        /// </summary>
        [Fact]
        public void _PayoutsTest()
        {
            // TODO unit test for the property '_Payouts'
        }

    }

}
