/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.104
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing PayoutsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayoutsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PayoutsResponse
        //private PayoutsResponse instance;

        public PayoutsResponseTests()
        {
            // TODO uncomment below to create an instance of PayoutsResponse
            //instance = new PayoutsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayoutsResponse
        /// </summary>
        [Fact]
        public void PayoutsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PayoutsResponse
            //Assert.IsType<PayoutsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Payouts'
        /// </summary>
        [Fact]
        public void PayoutsTest()
        {
            // TODO unit test for the property 'Payouts'
        }
        /// <summary>
        /// Test the property 'PaginationMetadata'
        /// </summary>
        [Fact]
        public void PaginationMetadataTest()
        {
            // TODO unit test for the property 'PaginationMetadata'
        }

    }

}
