/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.119
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing PostFirmBrandingColourRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostFirmBrandingColourRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostFirmBrandingColourRequest
        //private PostFirmBrandingColourRequest instance;

        public PostFirmBrandingColourRequestTests()
        {
            // TODO uncomment below to create an instance of PostFirmBrandingColourRequest
            //instance = new PostFirmBrandingColourRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostFirmBrandingColourRequest
        /// </summary>
        [Fact]
        public void PostFirmBrandingColourRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostFirmBrandingColourRequest
            //Assert.IsType<PostFirmBrandingColourRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Colour'
        /// </summary>
        [Fact]
        public void ColourTest()
        {
            // TODO unit test for the property 'Colour'
        }

    }

}
