/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.82
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing SurchargeChoice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SurchargeChoiceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SurchargeChoice
        //private SurchargeChoice instance;

        public SurchargeChoiceTests()
        {
            // TODO uncomment below to create an instance of SurchargeChoice
            //instance = new SurchargeChoice();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SurchargeChoice
        /// </summary>
        [Fact]
        public void SurchargeChoiceInstanceTest()
        {
            // TODO uncomment below to test "IsType" SurchargeChoice
            //Assert.IsType<SurchargeChoice>(instance);
        }



    }

}
