/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.163
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing SurchargeSettingsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SurchargeSettingsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SurchargeSettingsResponse
        //private SurchargeSettingsResponse instance;

        public SurchargeSettingsResponseTests()
        {
            // TODO uncomment below to create an instance of SurchargeSettingsResponse
            //instance = new SurchargeSettingsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SurchargeSettingsResponse
        /// </summary>
        [Fact]
        public void SurchargeSettingsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SurchargeSettingsResponse
            //Assert.IsType<SurchargeSettingsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'SurchargeSettings'
        /// </summary>
        [Fact]
        public void SurchargeSettingsTest()
        {
            // TODO unit test for the property 'SurchargeSettings'
        }

    }

}
