/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.164
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateArtifactAccountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateArtifactAccountRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateArtifactAccountRequest
        //private UpdateArtifactAccountRequest instance;

        public UpdateArtifactAccountRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateArtifactAccountRequest
            //instance = new UpdateArtifactAccountRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateArtifactAccountRequest
        /// </summary>
        [Fact]
        public void UpdateArtifactAccountRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateArtifactAccountRequest
            //Assert.IsType<UpdateArtifactAccountRequest>(instance);
        }


        /// <summary>
        /// Test the property 'NewAccountId'
        /// </summary>
        [Fact]
        public void NewAccountIdTest()
        {
            // TODO unit test for the property 'NewAccountId'
        }
        /// <summary>
        /// Test the property 'ArtifactType'
        /// </summary>
        [Fact]
        public void ArtifactTypeTest()
        {
            // TODO unit test for the property 'ArtifactType'
        }

    }

}
