/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.110
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookEventEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookEventEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookEventEvent
        //private WebhookEventEvent instance;

        public WebhookEventEventTests()
        {
            // TODO uncomment below to create an instance of WebhookEventEvent
            //instance = new WebhookEventEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookEventEvent
        /// </summary>
        [Fact]
        public void WebhookEventEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookEventEvent
            //Assert.IsType<WebhookEventEvent>(instance);
        }


        /// <summary>
        /// Test the property 'InvoiceId'
        /// </summary>
        [Fact]
        public void InvoiceIdTest()
        {
            // TODO unit test for the property 'InvoiceId'
        }
        /// <summary>
        /// Test the property 'FirmId'
        /// </summary>
        [Fact]
        public void FirmIdTest()
        {
            // TODO unit test for the property 'FirmId'
        }
        /// <summary>
        /// Test the property 'Matter'
        /// </summary>
        [Fact]
        public void MatterTest()
        {
            // TODO unit test for the property 'Matter'
        }
        /// <summary>
        /// Test the property 'Debtor'
        /// </summary>
        [Fact]
        public void DebtorTest()
        {
            // TODO unit test for the property 'Debtor'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'ExternalReference'
        /// </summary>
        [Fact]
        public void ExternalReferenceTest()
        {
            // TODO unit test for the property 'ExternalReference'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'AmountDue'
        /// </summary>
        [Fact]
        public void AmountDueTest()
        {
            // TODO unit test for the property 'AmountDue'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'SettlementAccountType'
        /// </summary>
        [Fact]
        public void SettlementAccountTypeTest()
        {
            // TODO unit test for the property 'SettlementAccountType'
        }
        /// <summary>
        /// Test the property 'SettlementAccountId'
        /// </summary>
        [Fact]
        public void SettlementAccountIdTest()
        {
            // TODO unit test for the property 'SettlementAccountId'
        }
        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Fact]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'Payments'
        /// </summary>
        [Fact]
        public void PaymentsTest()
        {
            // TODO unit test for the property 'Payments'
        }
        /// <summary>
        /// Test the property 'PaymentMethodsOverride'
        /// </summary>
        [Fact]
        public void PaymentMethodsOverrideTest()
        {
            // TODO unit test for the property 'PaymentMethodsOverride'
        }
        /// <summary>
        /// Test the property 'SurchargeChoiceOverride'
        /// </summary>
        [Fact]
        public void SurchargeChoiceOverrideTest()
        {
            // TODO unit test for the property 'SurchargeChoiceOverride'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'PaymentUri'
        /// </summary>
        [Fact]
        public void PaymentUriTest()
        {
            // TODO unit test for the property 'PaymentUri'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TrustDepositId'
        /// </summary>
        [Fact]
        public void TrustDepositIdTest()
        {
            // TODO unit test for the property 'TrustDepositId'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }
        /// <summary>
        /// Test the property 'PaymentType'
        /// </summary>
        [Fact]
        public void PaymentTypeTest()
        {
            // TODO unit test for the property 'PaymentType'
        }
        /// <summary>
        /// Test the property 'ArtifactId'
        /// </summary>
        [Fact]
        public void ArtifactIdTest()
        {
            // TODO unit test for the property 'ArtifactId'
        }
        /// <summary>
        /// Test the property 'ArtifactType'
        /// </summary>
        [Fact]
        public void ArtifactTypeTest()
        {
            // TODO unit test for the property 'ArtifactType'
        }
        /// <summary>
        /// Test the property 'ExternalPayment'
        /// </summary>
        [Fact]
        public void ExternalPaymentTest()
        {
            // TODO unit test for the property 'ExternalPayment'
        }
        /// <summary>
        /// Test the property 'Received'
        /// </summary>
        [Fact]
        public void ReceivedTest()
        {
            // TODO unit test for the property 'Received'
        }
        /// <summary>
        /// Test the property 'Refunded'
        /// </summary>
        [Fact]
        public void RefundedTest()
        {
            // TODO unit test for the property 'Refunded'
        }
        /// <summary>
        /// Test the property 'PaidOut'
        /// </summary>
        [Fact]
        public void PaidOutTest()
        {
            // TODO unit test for the property 'PaidOut'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'PayoutReference'
        /// </summary>
        [Fact]
        public void PayoutReferenceTest()
        {
            // TODO unit test for the property 'PayoutReference'
        }
        /// <summary>
        /// Test the property 'PayoutTotal'
        /// </summary>
        [Fact]
        public void PayoutTotalTest()
        {
            // TODO unit test for the property 'PayoutTotal'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Fact]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }
        /// <summary>
        /// Test the property 'Artifacts'
        /// </summary>
        [Fact]
        public void ArtifactsTest()
        {
            // TODO unit test for the property 'Artifacts'
        }
        /// <summary>
        /// Test the property 'AmountPaid'
        /// </summary>
        [Fact]
        public void AmountPaidTest()
        {
            // TODO unit test for the property 'AmountPaid'
        }
        /// <summary>
        /// Test the property 'CardPayment'
        /// </summary>
        [Fact]
        public void CardPaymentTest()
        {
            // TODO unit test for the property 'CardPayment'
        }
        /// <summary>
        /// Test the property 'DebitPayment'
        /// </summary>
        [Fact]
        public void DebitPaymentTest()
        {
            // TODO unit test for the property 'DebitPayment'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'PaymentMethodDetail'
        /// </summary>
        [Fact]
        public void PaymentMethodDetailTest()
        {
            // TODO unit test for the property 'PaymentMethodDetail'
        }
        /// <summary>
        /// Test the property 'LegalName'
        /// </summary>
        [Fact]
        public void LegalNameTest()
        {
            // TODO unit test for the property 'LegalName'
        }
        /// <summary>
        /// Test the property 'TradingName'
        /// </summary>
        [Fact]
        public void TradingNameTest()
        {
            // TODO unit test for the property 'TradingName'
        }
        /// <summary>
        /// Test the property 'PaymentStatus'
        /// </summary>
        [Fact]
        public void PaymentStatusTest()
        {
            // TODO unit test for the property 'PaymentStatus'
        }
        /// <summary>
        /// Test the property 'FailureMessage'
        /// </summary>
        [Fact]
        public void FailureMessageTest()
        {
            // TODO unit test for the property 'FailureMessage'
        }

    }

}
