/*
 * FeeWise Partner API
 *
 * API for partners
 *
 * The version of the OpenAPI document: 0.0.45
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FeeWise.Api;
using FeeWise.Model;
using FeeWise.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FeeWise.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookApiAuthentication
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookApiAuthenticationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookApiAuthentication
        //private WebhookApiAuthentication instance;

        public WebhookApiAuthenticationTests()
        {
            // TODO uncomment below to create an instance of WebhookApiAuthentication
            //instance = new WebhookApiAuthentication();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookApiAuthentication
        /// </summary>
        [Fact]
        public void WebhookApiAuthenticationInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookApiAuthentication
            //Assert.IsType<WebhookApiAuthentication>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'AddPosition'
        /// </summary>
        [Fact]
        public void AddPositionTest()
        {
            // TODO unit test for the property 'AddPosition'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
